object_info = {'Person': 'A human being.',
               'Bicycle': 'A human-powered, pedal-driven vehicle with two wheels.',
               'Car': 'A four-wheeled motor vehicle used for transportation.',
               'Motorcycle': 'A two-wheeled motor vehicle.',
               'Airplane': 'A powered flying vehicle with fixed wings.',
               'Bus': 'A large motor vehicle carrying passengers by road.',
               'Train': 'A series of connected vehicles that run on tracks.',
               'Truck': 'A large, heavy motor vehicle for transporting goods.',
               'Boat': 'A small vessel for traveling on water.',
               'Traffic light': 'A signaling device at road intersections.',
               'Fire hydrant': 'An outlet from a water main for fighting fires.',
               'Stop sign': 'A traffic sign instructing vehicles to stop.',
               'Parking meter': 'A device for collecting parking fees.',
               'Bench': 'A long seat for several people, typically made of wood or metal.',
               'Bird': 'A warm-blooded, egg-laying vertebrate with feathers.',
               'Cat': 'A small domesticated carnivorous mammal.',
               'Dog': 'A domesticated carnivorous mammal.',
               'Horse': 'A large herbivorous mammal with solid hooves.',
               'Sheep': 'A domesticated ruminant mammal with a thick woolly coat.',
               'Cow': 'A domesticated bovine animal.',
               'Elephant': 'A large herbivorous mammal with a trunk.',
               'Bear': 'A large mammal with shaggy hair, a short tail, and sharp claws.',
               'Zebra': 'An African wild horse with black-and-white stripes.',
               'Giraffe': 'A tall African mammal with a very long neck and legs.',
               'Backpack': 'A bag with shoulder straps carried on the back.',
               'Umbrella': 'A device for protection against rain or sun.',
               'Handbag': 'A small bag used by women to carry personal items.',
               'Tie': 'A long piece of cloth worn around the neck.',
               'Suitcase': 'A rectangular bag for carrying clothes and other personal items.',
               'Frisbee': 'A plastic disc used as a toy for throwing.',
               'Skis': 'Long, narrow pieces of wood or metal for gliding over snow.',
               'Snowboard': 'A board used for sliding down snow-covered slopes.',
               'Sports ball': 'A ball used in various sports (e.g., soccer, basketball).',
               'Kite': 'A light frame with thin material flown in the wind at the end of a string.',
               'Baseball bat': 'A smooth wooden or metal club used in baseball.',
               'Baseball glove': 'A large leather glove worn by baseball players.',
               'Skateboard': 'A board with four wheels ridden in a standing or crouching position.',
               'Surfboard': 'A long, narrow board used for riding waves in the ocean.',
               'Tennis racket': 'A racket used for playing tennis.',
               'Bottle': 'A container with a narrow neck used for storing liquids.',
               'Wine glass': 'A glass with a stem used for drinking wine.',
               'Cup': 'A small open container used for drinking.',
               'Fork': 'A utensil with two or more prongs used for eating.',
               'Knife': 'A tool with a blade used for cutting.',
               'Spoon': 'A utensil with a shallow bowl used for eating or serving.',
               'Bowl': 'A round, deep dish used for food or liquid.',
               'Banana': 'A long curved fruit with a yellow skin.',
               'Apple': 'A round fruit with red, green, or yellow skin.',
               'Sandwich': 'Two slices of bread with a filling in between.',
               'Orange': 'A citrus fruit with a tough bright reddish-yellow rind.',
               'Broccoli': 'A vegetable with a large green flower head.',
               'Carrot': 'A long, orange root vegetable.',
               'Hot dog': 'A cooked sausage served in a sliced bun.',
               'Pizza': 'A dish made with a dough base topped with ingredients and baked.',
               'Donut': 'A small fried cake of sweetened dough.',
               'Cake': 'A sweet baked dessert usually made from flour, sugar, and eggs.',
               'Chair': 'A seat with a back, typically having four legs.',
               'Couch': 'A piece of furniture for seating multiple people.',
               'Potted plant': 'A plant grown in a container.',
               'Bed': 'A piece of furniture for sleeping on.',
               'Dining table': 'A table at which meals are eaten.',
               'Toilet': 'A fixture for urination and defecation.',
               'TV': 'A device for receiving television broadcasts.',
               'Laptop': 'A portable personal computer.',
               'Mouse': "A hand-held device used to control a computer's cursor.",
               'Remote': 'A device used to control electronic equipment wirelessly.',
               'Keyboard': 'A panel of keys for typing on a computer.',
               'Cell phone': 'A portable telephone.',
               'Microwave': 'An appliance for cooking food using microwaves.',
               'Oven': 'An appliance for baking or roasting food.',
               'Toaster': 'A device for toasting bread.',
               'Sink': 'A basin used for washing.',
               'Refrigerator': 'An appliance for keeping food and drinks cold.',
               'Book': 'A set of written or printed pages bound together.',
               'Clock': 'A device for measuring and indicating time.',
               'Vase': 'A container used for holding flowers.',
               'Scissors': 'A cutting instrument with two blades.',
               'Teddy bear': 'A soft toy in the shape of a bear.',
               'Hair drier': 'An electrical device for drying hair.',
               'Toothbrush': 'A small brush used for cleaning teeth.'}
